### ISSUE TITLE
doc: Node PATH may be broken if MacOS was upgraded from Bash to ZSH

### ISSUE THREAD

**Issue by coolaj86** [dashhive/crowdnode-cli#10]
Re: https://github.com/dashhive/crowdnode-cli/issues/9#issuecomment-1175738602

This is an important concern, but it's not one that I know we can do anything about other than document.

It may also be difficult to find machines that have this problem and to reproduce it.

Confirmed that installing via Webi and closing and re-opening the Terminal fixes it.

**Comment by riongull** [comment]
We'll see if any other testers come across this issue.  Closing for now.
