### ISSUE TITLE
doc: wording on sending to staking key

### ISSUE THREAD

**Issue by coolaj86** [dashhive/crowdnode-cli#12]
Re: https://github.com/dashhive/crowdnode-cli/issues/9#issuecomment-1175761497

Fewer words the better.

I can count on my hands the number of times I've witnessed people reading what's on their screen. Those people are all making 6+ figure incomes.

How about this?

> Send Đ{effectiveDash} to your staking key via the QR above, or its address:
> {addr}
> (this key will be used to fund and control your CrowdNode account)

I think that's a whole line too long. I don't know that this program should really be the educational material about how the process works in fine detail.

I think that may be better left to a blog.

Can we figure out a way to _reduce_ the information rather than increase it?

**Comment by riongull** [comment]
> I think that may be better left to a blog.

Agreed (https://github.com/dashhive/crowdnode-cli/issues/15#issuecomment-1176624139)

We'll close this with merged PR above
