### ISSUE TITLE
Version Information

### ISSUE THREAD

**Issue by riongull** [dashhive/crowdnode-cli#17]
Might make sense to have the one or more of the following version-related things:

1. A command or flag to return the current `crowdnode-cli` version.
2. A notification of some sort when an updated version is available.
3. A command to update the CLI

Thoughts @coolaj86?

**Comment by riongull** [comment]
Just realized item 1 above is taken care of:

```
14:48:59 [~] % crowdnode help  
crowdnode v1.6.0 - Manage your stake in Đash with the CrowdNode Blockchain API
```

Still may be nice to have something shorter than the help command, like `crowdnode --version`.

**Comment by coolaj86** [comment]
`--version` `-V` and `version` all work. The first two are the standard BSD / Linux flags that (almost) all *nix programs support. The 3rd is what many of the more modern CLI tools support.

```txt
crowdnode --version
crowdnode v1.6.0 - Manage your stake in Đash with the CrowdNode Blockchain API

crowdnode -V
crowdnode v1.6.0 - Manage your stake in Đash with the CrowdNode Blockchain API

crowdnode version
crowdnode v1.6.0 - Manage your stake in Đash with the CrowdNode Blockchain API
```

**Comment by riongull** [comment]
Ah. Great. I don't recall seeing it in the help menu (is it?). I should have at least tried it.

**Comment by coolaj86** [comment]
Added in https://github.com/dashhive/crowdnode.js/pull/35
