### ISSUE TITLE
`crowdnode status` displays excessive precision

### ISSUE THREAD

**Issue by riongull** [dashhive/crowdnode-cli#19]
@coolaj86, it looks like `crowdnode status` displays excessive precision.

> CrowdNode Stake: 400307268 (Đ4.0030726763)

It should only have 8 digits after the decimal.

_Originally posted by @riongull in https://github.com/dashhive/crowdnode-cli/issues/16#issuecomment-1178475830_

**Comment by coolaj86** [comment]
This is a bug in the CrowdNode API, but we can fix it on our side as a workaround:

```js
let crowdNodeBalance = await CrowdNode.http.GetBalance(addr);
console.log(crowdNodeBalance.TotalBalance); // shows exactly what CrowdNode gives us
```

Could you try your key against the CrowdNode API directly to confirm?

```bash
my_addr="YOUR_KEY_GOES_HERE"

curl -fsSL "https://app.crowdnode.io/odata/apifundings/GetBalance(address='${my_addr}')"
```

**Comment by coolaj86** [comment]
Also, the time has too much precision:

```txt
"UpdatedOn": "2022-07-02T15:29:55.8533333"
```

I really don't care if it's been 1/3 of a millisecond... :)

**Comment by coolaj86** [comment]
This is fixed as part of https://github.com/dashhive/crowdnode.js/pull/35
