### ISSUE TITLE
Withdraw (verb) & withdrawal (noun)

### ISSUE THREAD

**Issue by riongull** [dashhive/crowdnode-cli#21]
Let's make sure all references to withdraw and withdrawal are grammatically correct
- use "withdraw" when it's a verb
- use "withdrawal" when it's a noun

(same as https://github.com/dashhive/crowdnode.js/issues/33)

**Comment by coolaj86** [comment]
Fixed as part of https://github.com/dashhive/crowdnode.js/pull/35
