### ISSUE TITLE
ZephiraReview crowdnode cli

### ISSUE THREAD

**Issue by ZephiraDev** [dashhive/crowdnode-cli#24]
Dear. The CLI tool installed with no issues on  Ubuntu 20.04.3 LTS Server. 
I used ansible to provision the requirements (nodeJS) on a VM. 
I have no problems to report. Everything went smooth and is straightforward. 

Will test the withdrawal function in a few weeks. 

![cli-staking](https://user-images.githubusercontent.com/111899852/211929673-0009266c-d734-4f32-b749-038020176b68.png)

**Comment by ZephiraDev** [comment]
Hello. Today I have tried withrawal feature and have received an error : 
I can ping and dns lookup addresses from google so its not a connection error at my side

![image](https://user-images.githubusercontent.com/111899852/214117104-21a0d200-6f8d-44ab-8869-dc92ce7df9f2.png)



>

**Comment by coolaj86** [comment]
My initial thought that this might be an IPv6 issue seems to not be the case.

Try running `dig +trace dashsight.dashincubator.dev` a few times on your computer. That may help clear your computer's local DNS cache, and refresh your router and/or ISP as well.

The records are set properly and I get back the expected results:

Short

```sh
dig +short dashsight.dashincubator.dev
```

```text
164.92.69.110
```

Trace

```sh
dig +trace dashsight.dashincubator.dev
```

```text
;; Received 1109 bytes from 192.168.0.1#53(192.168.0.1) in 1 ms

dashsight.dashincubator.dev. 259 IN	A	164.92.69.110
```

**Comment by ZephiraDev** [comment]
> My initial thought that this might be an IPv6 issue seems to not be the case.
> 
Hello. I disabled IPV6 on the host machine. then I tried withdraw again and it worked (VM inside host machine): 


![stake_OK](https://user-images.githubusercontent.com/111899852/215125242-7702c234-9f79-4670-9f46-feafd18aaf1f.png)

am getting back this from the dig+ trace :  dashsight.dashincubator.dev. 259 IN	A	164.92.69.110
